---
- name: Deploy Docker Container
  hosts: all
  gather_facts: false
  vars:
    image_tag: latest
    bind_port: 8000
    container_port: 8000
    container_name: make-python-devex-bt
    image_name: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}/make-python-devex-bt"
    docker_registry: "{{ lookup('env', 'CI_REGISTRY') }}"
    docker_username: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
    docker_password: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"

  tasks:
    - name: Debug input variables
      debug:
        msg:
          - "DEBUG: Received parameters:"
          - "  IMAGE_TAG: {{ image_tag }}"
          - "  BIND_PORT: {{ bind_port }}"
          - "  DOCKER_REGISTRY: {{ docker_registry }}"
          - "  DOCKER_USERNAME: {{ docker_username }}"
          - "  DOCKER_PASSWORD: {{ docker_password }}"

    - name: Fail if required parameters are missing
      fail:
        msg: "Required parameters are missing. Ensure IMAGE_TAG, BIND_PORT, DOCKER_REGISTRY, DOCKER_USERNAME, and DOCKER_PASSWORD are provided."
      when: image_tag == "" or bind_port == "" or docker_registry == "" or docker_username == "" or docker_password == ""

    - name: Check if port {{ bind_port }} is in use
      shell: |
        netstat -tuln | grep ":{{ bind_port }}"
      register: port_check
      ignore_errors: true

    - name: Debug port check output
      debug:
        msg: "{{ port_check.stdout }}"

    - name: Stop the service using port {{ bind_port }} if found
      shell: |
        fuser -k {{ bind_port }}/tcp
      when: port_check.rc == 0
      ignore_errors: true

    - name: Log in to Docker registry
      community.docker.docker_login:
        registry_url: "{{ docker_registry }}"
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Pull the Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Stop and remove the old container (if exists)
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Run the new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        ports:
          - "{{ bind_port }}:{{ container_port }}"
        state: started
